import pg from 'pg';

/**
 * Admin connection used to create and drop throwaway test databases.
 * Defaults to the docker-compose `postgres` service (`npm run db:up`).
 */
export const ADMIN_URL = process.env.TEST_DATABASE_URL ?? 'postgres://tasks:tasks@localhost:5432/postgres';

/** Migrated once per run; every test file clones it (CREATE DATABASE … TEMPLATE), which takes ~100ms. */
export const TEMPLATE_DB = 'tasks_test_template';
export const TEST_DB_PREFIX = 'tasks_test_';

export function urlFor(database: string): string {
  const url = new URL(ADMIN_URL);
  url.pathname = `/${database}`;
  return url.toString();
}

export async function withAdmin<T>(fn: (client: pg.Client) => Promise<T>): Promise<T> {
  const client = new pg.Client({ connectionString: ADMIN_URL, connectionTimeoutMillis: 5_000 });
  await client.connect();
  try {
    return await fn(client);
  } finally {
    await client.end();
  }
}

/** Database names are generated by the test code, never user input; quoting keeps them valid identifiers. */
export const quoteIdent = (name: string) => `"${name.replaceAll('"', '""')}"`;

export async function dropTestDatabases(): Promise<void> {
  await withAdmin(async (client) => {
    const { rows } = await client.query<{ datname: string }>(
      `SELECT datname FROM pg_database WHERE datname LIKE $1`,
      [`${TEST_DB_PREFIX.replaceAll('_', '\\_')}%`],
    );
    for (const { datname } of rows) await client.query(`DROP DATABASE IF EXISTS ${quoteIdent(datname)} WITH (FORCE)`);
  });
}
