import { fileURLToPath } from 'node:url';
import { drizzle, type NodePgDatabase } from 'drizzle-orm/node-postgres';
import pg from 'pg';
import * as schema from './schema.js';

export type Database = NodePgDatabase<typeof schema>;

/** SQL migrations generated by drizzle-kit. Resolves the same from src/db (tsx) and dist/db (compiled). */
export const MIGRATIONS_FOLDER = fileURLToPath(new URL('../../drizzle', import.meta.url));

export function createPostgresDatabase(url: string, poolMax: number): { db: Database; close: () => Promise<void> } {
  const pool = new pg.Pool({
    connectionString: url,
    max: poolMax,
    connectionTimeoutMillis: 5_000,
    idleTimeoutMillis: 30_000,
    // Fail a stuck query instead of holding a pool connection forever.
    statement_timeout: 10_000,
    application_name: 'tasks-api',
  });
  let closed = false;
  return {
    db: drizzle(pool, { schema }),
    close: async () => {
      if (closed) return;
      closed = true;
      await pool.end();
    },
  };
}
